version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    container_name: drivenation-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: drivenation
      MONGO_INITDB_ROOT_PASSWORD: drivenation
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  mongodbdata: